### ISSUE TITLE
Integrations doc makes reference to non-existent section [BUG]

### ISSUE THREAD

**Issue by orlando21** [Mirascope/mirascope#179]
**To Reproduce**

Go to 'https://docs.mirascope.io/latest/concepts/integrations/#langchain-and-langsmith'

The text says "You can use client wrappers (as mentioned in the first section of this doc) to integrate Mirascope with LangSmith"

However, the first section of that file talks about Weights & Biases `weave` method.

The text "(as mentioned in the first section of this doc)" should probably be removed.

**Comment by willbakst** [comment]
Good catch! It's supposed to reference the section directly above it, not the first section.

**Comment by willbakst** [comment]
Docs are updated with a fix!

https://docs.mirascope.io/latest/concepts/integrations/#langchain-and-langsmith
