### ISSUE TITLE
Documentation suggests a hyperlink where there isn't one[BUG]

### ISSUE THREAD

**Issue by orlando21** [Mirascope/mirascope#189]
1. Go to https://github.com/Mirascope/mirascope/blob/dev/docs/concepts/attaching_and_calling_tool_functions.md
2. Scroll down to the paragraph 'The tools are attached to the call_params attribute in a Mirascope Call. For more information check out Learn why colocation is so important and how combining it with the [Mirascope CLI](https://github.com/Mirascope/mirascope-cli) makes engineering better prompts and calls easy.'
3. Error: '..check out Learn why colocation is so important..." Should this be linked to somewhere else in the docs?

**Comment by willbakst** [comment]
Good catch! I've updated the wording, added the missing link, and redeployed the docs :)

https://docs.mirascope.io/latest/concepts/attaching_and_calling_tool_functions/
