### ISSUE TITLE
Mirascope CLI doc page has been moved or removed, resulting in 404s throughout the blog [BUG]

### ISSUE THREAD

**Issue by orlando21** [Mirascope/mirascope#193]
**To Reproduce**

1. Go to any blog page and click a hyperlink anchor concerning Mirascope's CLI.  (e.g., go to https://www.mirascope.io/post/langchain-prompt-template)
2. The referenced URL is https://docs.mirascope.io/latest/concepts/using_the_mirascope_cli/, now a missing page

**Additional context**
Also, I cannot find the Mirascope CLI page via docs search.

**Comment by willbakst** [comment]
Thanks for pointing this out! We are working on fixing the links now.

We've moved the CLI to it's [own repo](https://github.com/Mirascope/mirascope-cli) which is why you can't find it via search. The documentation is now located in the new repo's README.md

**Comment by willbakst** [comment]
This should now be resolved :)
