### ISSUE TITLE
[BUG] Not seeing OpenAI-related logs populating in logfire UI

### ISSUE THREAD

**Issue by barapa** [Mirascope/mirascope#199]
In my terminal logs, I see
```
legaide_api  | 17:34:18.571     Generating extractor
legaide_api  | 17:34:18.576     Calling LLM
legaide_api  | 17:34:18.577     LLMHearingExtractor.extract_async
legaide_api  | 17:34:18.586     Pydantic TempCall validate_python
legaide_api  | 17:34:18.739     Chat Completion with 'gpt-4-turbo'
legaide_api  | 17:34:49.404     Pydantic HearingOverviewExtraction validate_python
```

So it looks like that I coming from Mirascope. But in the logfire UI, I don't see anything re: OpenAI calls in the span:

![Screenshot 2024-04-30 at 1 36 27 PM](https://github.com/Mirascope/mirascope/assets/653637/a6455d77-5771-4516-97d5-4243abc1779f)

Have you seen the OpenAI call details populate in the logfire UI? Not sure if this is a logfire issue or Mirascope yet.

**Comment by willbakst** [comment]
Hi @barapa! We have seen OpenAI (and other provider calls) populate in the UI (there is a + icon for nested spans, and inside the nested structure is where the OpenAI call is).

<img width="809" alt="Screenshot 2024-04-30 at 10 57 01 AM" src="https://github.com/Mirascope/mirascope/assets/99370834/68df050e-7a8e-4ad9-a5a2-d73da737e005">

I just tested this with the following FastAPI example:

```python
import os
from typing import Type

import logfire
from fastapi import FastAPI
from pydantic import BaseModel

from mirascope.logfire import with_logfire
from mirascope.openai import OpenAIExtractor

os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_API_KEY"

app = FastAPI()
logfire.configure()
logfire.instrument_fastapi(app)


class Book(BaseModel):
    title: str
    author: str


@with_logfire
class BookRecommender(OpenAIExtractor[Book]):
    extract_schema: Type[Book] = Book
    prompt_template = "Please recommend a {genre} book."

    genre: str


@app.post("/")
async def root(book_recommender: BookRecommender) -> Book:
    """Generates a book based on provided `genre`."""
    return await book_recommender.extract_async()
```

**Comment by barapa** [comment]
Ha yes, I didn't see the nested traces! Thank you.

In running an extraction, I don't see the `assistant` box filled out:
![Screenshot 2024-04-30 at 2 02 10 PM](https://github.com/Mirascope/mirascope/assets/653637/a9f0ca1b-b548-441d-bb92-70f692e4d2f8)

Is that your experience when using an extractor as well?

**Comment by barapa** [comment]
I think this may be because the response is a function call.

**Comment by barapa** [comment]
OK, this is not a bug. Closing.

**Comment by willbakst** [comment]
Unfortunately it looks like logfire has a bug with `instrument_openai` calls nested inside of `instrument_fastapi`.

I will followup with the team to see what is going on there.

We are currently working on additional support for other providers and will be releasing that later today (confirmed to work locally).

**Comment by willbakst** [comment]
Oh yeah you're totally right, it's due to function calling.

I will look into how we might be able to better support this (although will likely require additional handling with logfire).

I believe they are releasing a customizable UI kit that we could use here, so will circle back when that is released.

For now the function calls should be present in the response data (just not pretty like the messages UI)

**Comment by willbakst** [comment]
They are officially working on this now :)
