### ISSUE TITLE
Why do we have indentation in the prompt template?

### ISSUE THREAD

**Issue by off6atomic** [Mirascope/mirascope#240]
### Question

```py
@tags(["version:0003"])
class Editor(OpenAICall):
    prompt_template = """
    SYSTEM:
    You are a top class manga editor.
    
    USER:
    I'm working on a new storyline. What do you think?
    {storyline}
    """

    storyline: str

    call_params = OpenAICallParams(model="gpt-4o", temperature=0.4)
```

I noticed that there's a bunch of whitespaces in front of the prompt template. Is this automatically removed or is it sent to OpenAI as is?
If it's sent to OpenAI as is, it might cost some tokens so I am curious about the reasoning behind this design.

**Comment by brenkao** [comment]
All the whitespace is automatically striped. When you call `Editor(storyline="...").messages()`, you should be able to see what is will be sent to OpenAI.
We will update our docs to make this more clear, thanks for using our library!

**Comment by willbakst** [comment]
Please also note that when writing multi-line prompts that the content for each message needs to be on a new line for proper dedent parsing:

https://docs.mirascope.io/latest/concepts/writing_prompts/#multi-line-messages

**Comment by willbakst** [comment]
Also one thing I forgot the mention. You asked "why" we have whitespace in the prompt template. This is not actually required, we just strip it for you if you want to take advantage of that functionality. For example, the following still works:

```python
@tags(["version:0003"])
class Editor(OpenAICall):
    prompt_template = """
SYSTEM:
You are a top class manga editor.

USER:
I'm working on a new storyline. What do you think?
{storyline}
"""

    storyline: str

    call_params = OpenAICallParams(model="gpt-4o", temperature=0.4)
```

However, we find this isn't as readable and doesn't look as nice in code, so we offer the automatic removal of the whitespace for convenience and readability.

**Comment by off6atomic** [comment]
Cool, I think it's a good magic to have. It just needs to be told to the user that this happens as early as possible I think.

**Comment by off6atomic** [comment]
I think in the first example tutorial, maybe you can write comment "Don't worry about the indentation, it's automatically removed so there won't be extra tokens cost"
This objection happens unconsciously and it could make people think that Mirascope didn't care about cost optimization.

**Comment by willbakst** [comment]
We updated the first example to say "white-space is automatically stripped"

Hopefully this is clear enough, but if not we can always update.
