### ISSUE TITLE
OpenAI GPT `tool_choice="required"` finishes with stop reason `stop` which throws error even though tool is called

### ISSUE THREAD

**Issue by willbakst** [Mirascope/mirascope#256]
### Description

For some reason calling GPT models while requiring the use of tools no longer has the correct stop reason.

Ideally in the event that `tool_choice="required"` we should be ok with any stopping reason so long as there is a tool.

**Comment by willbakst** [comment]
@dearkafka this is released in v0.13.3 :)

You can set `tool_choice="required"` in `call_params` or as a keyword arg and it should work

**Comment by dearkafka** [comment]
thanks 🙏
