### ISSUE TITLE
Why is Mirascope failing on NER beyond 2 levels?

### ISSUE THREAD

**Issue by willbakst** [Mirascope/mirascope#259]
Marie Stephen Leo [posted about Mirascope on LinkedIn](https://www.linkedin.com/posts/marie-stephen-leo_generativeai-llm-nlp-activity-7197762887757541376-wqxZ?utm_source=share&utm_medium=member_desktop) and noted that it missed a single deep nested field in the third nested level of an NER task (and it looks like in the original post before this one that fructose succeeds for this task).

Why is this the case? I think this is something worth looking into. If fructose can do it, then there must be a way for Mirascope to do it without having to wait on model improvements.

Want to use this as an open discussion as I look deeper into why this might be the case and how we can make Mirascope structured extraction as good as possible (with solving this failure as the next step).

**Comment by KTS-o7** [comment]
One rudimentary idea i can think is to first split the input and call recursively ? Like lets say Entitiy 1 -> entity2 -> entity 3 when recognise Entity 1 and than pass rest of input again to another call then combine.. totally it would need multiple calls on same input text ?

**Comment by KTS-o7** [comment]
I will try something based on what the recent reflection models are doing.. logical reasoning should be tried i feel

**Comment by willbakst** [comment]
In the original post from Marie, he points out that he didn't do anything beyond the basics of using extraction.

I'm less curious about prompt engineering to get the correct result and more curious about how `fructose` was able to get the correct output without additional prompt engineering where it seems `mirascope` failed.

What did `fructose` do that enabled better results, and is there something there that we can apply in `mirascope`?

**Comment by KTS-o7** [comment]
I was checking with `fructose`. In that project under `src/llm_handler.py` there is a reasoning function defined. I haven't gone through it completely as of now. But might be pointing to something 
[Link to the functions in `fructose`](https://github.com/bananaml/fructose/blob/5f24ec0f773170d5f55fe520fa7436f69b1a4f65/src/fructose/llm_function_handler.py#L124)

**Comment by willbakst** [comment]
oh interesting, it would make sense if they are using more complex reasoning internally how they would get better results out-of-the-box. We should not be including such updates to a user's prompt, so this seems like a moot point given that the effort to match their results really falls on the user and their specific task. Thanks for checking this out.

If you'd like to contribute, a cookbook showing how to prompt engineer success on this NER task would be awesome!

**Comment by KTS-o7** [comment]
yeah i am doing that.. might take me a little bit of time tho. Im juggling my semester end exams and coding. Happy to contribute !

**Comment by willbakst** [comment]
no rush, good luck with exams!

we're here to help your contribution however we can :)

**Comment by KTS-o7** [comment]
Added a rudimentary implementation.. what exactly are we looking for and how i can improve my contribution and be of actual use ? XD

**Comment by willbakst** [comment]
Just submitted my review of the PR, great stuff!

I've left comments wrt. improvements, and I think once we address those this recipe will be super useful and informative.

**Comment by KTS-o7** [comment]
Added a new commit. Fixed most issues that were pointed out, eager for ur comments.

**Comment by KTS-o7** [comment]
We can probably close this issue.
