### ISSUE TITLE
Missing models for Cohere cost calculations

### ISSUE THREAD

**Issue by brenkao** [Mirascope/mirascope#269]
### Description

Currently our [cohere_api_calculate_cost](https://github.com/Mirascope/mirascope/blob/dev/mirascope/cohere/utils.py) function only contains `command-r` and `command-r-plus` models. All models in https://cohere.com/pricing and https://docs.cohere.com/docs/models should be added to the cost function such that when a user uses any cohere model, they have cost calculation

**Comment by tvj15** [comment]
Hi, I was working on this issue and I saw that Cohere uses rerank models for their rerank functionality (https://cohere.com/pricing). But, there is no implementation for the same in Mirascope. So should I add those models as well in the cost calculations or could I skip them?

**Comment by willbakst** [comment]
Hi @tvj15! Right now we only support the `/chat` endpoints for our call and extraction classes. It's fine to skip the rerank and other such models and add cost tracking support just for the currently supported models.

If general support for those models is something you're interested in, feel free to file a feature request.

Given you're working on this issue, I've assigned it to you so others know it's taken :)

**Comment by tvj15** [comment]
> Hi @tvj15! Right now we only support the `/chat` endpoints for our call and extraction classes. It's fine to skip the rerank and other such models and add cost tracking support just for the currently supported models.
> 
> If general support for those models is something you're interested in, feel free to file a feature request.
> 
> Given you're working on this issue, I've assigned it to you so others know it's taken :)

In that case, only command-r and command-r-plus models are used for the /chat endpoint. There are other models (command, command-light, command-nightly, command-light-nightly) that are used by  /chat endpoint but they seem to be deprecated and I can not find pricing for these models.

**Comment by willbakst** [comment]
Oh, you're totally right. I just took a look myself and couldn't find pricing for any of those models...

**Comment by willbakst** [comment]
@tvj15 I marked this as invalid and am going to close the issue given this finding. Thank you for pointing this out!

I apologize for the confusion.

https://github.com/Mirascope/mirascope/issues/218 is another good first issue if you're interested in taking that instead, and we can provide support as necessary :)
