### ISSUE TITLE
Mismatch in the comment and the code for properties of CohereCallResponseChunk class

### ISSUE THREAD

**Issue by tvj15** [Mirascope/mirascope#293]
In the code below, the comment says that the `response` property returns the response for the text-generation event type. But the code checks for Stream End (`StreamedChatResponse_StreamEnd`) event type.

```python
@property
    def response(self) -> Optional[NonStreamedChatResponse]:
        """Returns the response for text-generation event type else None."""
        if isinstance(self.chunk, StreamedChatResponse_StreamEnd):
            return self.chunk.response
        return None
```
The similar thing goes here:
```python
  @property
    def documents(self) -> Optional[list[ChatDocument]]:
        """Returns the documents for citation-generation event type else None."""
        if isinstance(self.chunk, StreamedChatResponse_SearchResults):
            return self.chunk.documents
        return None
```

**Comment by willbakst** [comment]
So I believe the first one is actually correct. The `StreamedChatResponse_StreamEnd` chunk type has a `response` property that returns the `NonStreamedChatResponse` instance, which has the same type as the standard text-generation event (and the full response for the entire text-generation stream). Maybe this could be more clear, something like "Returns the full response for the stream-end event type else None."?

The second one should say "search-results event type" I believe, good catch!

Want to open a PR with the fix?
