### ISSUE TITLE
How can we implement an agent that describe its plan before calling tools to execute the plan?

### ISSUE THREAD

**Issue by off6atomic** [Mirascope/mirascope#304]
### Question

Typically when we make an agent, (for example, a math agent), the agent will repeatedly call tools until it eventually produces a text response. I can enable this repetition by simply calling the API again as long as the last response is a tool message.
Here is example math agent with said behavior: https://github.com/Mirascope/mirascope/issues/262#issuecomment-2126436017
The line that enables repetition is this line: `while mathematician.history[-1]["role"] == "tool":`

But what about the opposite? Instead of calling tools repeatedly, followed by text response, what if I want to generate text response first followed by calling tools?

Suppose the agent want to produce a text response to tell its plan e.g. `To evaluate sqrt(5*8) I will multiply 5 and 8 first then take their square root. I need to call multiply tool, wait for the output, and then call sqrt tool. I'm starting now.`
then it will want to call tools to pursue this goal. However, it's not clear to me how to know that the agent want to call tools so that I can call the agent again without waiting for user input.

How do we know that the agent wants to call tools after it has returned text response?

### End goal
**Implement an agent that can describe its plan before performing tool calling.**

If there's a smarter way to achieve this goal, please let me know.

**Comment by willbakst** [comment]
Two recommendations here:
1. You can always write this as two separate calls or a chain. If you want to guarantee that the first step the agent takes is creating a plan, I would engineer a call that's really good at generating the plan that you then feed into the agent.
2. If you want to let the agent decide if it should plan (or re-plan), you can create a planning tool that you let the agent call.

**Comment by off6atomic** [comment]
I think the 2nd recommendation is more suitable. That's what I thought as well but it sounds like a headache to implement streaming for this tool. Usually I just treat all tools as generating an output once, not streaming output.

In my opinion, OpenAI should handle generating a text response and tool call afterwards. In that case, we don't have to do all this hacking. Anyway it seems like they don't support it so we need to cope.

2 solutions after seeing your recommendations:
1. Maybe we need to think about how to handle tools that can stream results. OpenAI doesn't handle this internally so we have to think of a system on top that will allow us to do this. For use case, think of the accordion in the web UI that you can open to see that the model is thinking about something.
2. We could also just create a different call that is for checking whether the last text response contains an intent to call another tool. This call needs to always be executed on every text response so it needs to be fast. Think of it similar to the data extractor call. By the way, maybe [data extractor](https://docs.mirascope.io/latest/#extracting-structured-information) is the right tool for this job?

**Comment by willbakst** [comment]
> Maybe we need to think about how to handle tools that can stream results.

You can already do this. You're the one calling the function, so you can do whatever you want with it.

```python
def planning_tool(...) -> Generator[str, None, None]:
    for chunk in PlanningCall().stream():
        yield chunk.content

...

if tools := response.tools:
    for tool in tools:
        if tool.name == planning_tool.__name__:
            plan = ""
            for chunk_content in tool.call():
                do_something_with_chunk(chunk_content)
                plan += chunk_content
            do_something_with_plan(plan)
        else: ...
```

> By the way, maybe [data extractor](https://docs.mirascope.io/latest/#extracting-structured-information) is the right tool for this job?

For the above, just use an extractor if you want:

```python
class Plan(BaseModel):
    ...

class PlanExtractor(OpenAIExtractor[Plan]):
    ...

def planning_tool(...) -> Generator[Partial[Plan], None, None]:
    for plan in PlanExtractor().stream():
        yield plan

...

if tools := response.tools:
    for tool in tools:
        if tool.name == planning_tool.__name__:
            plan = None
            for partial_plan in tool.call():
                do_something_with_partial_plan(partial_plan)
                plan = partial_plan
            do_something_with_plan(plan)
        else: ...
```

> In my opinion, OpenAI should handle generating a text response and tool call afterwards. 

Some model providers actually do this. They provide a list of content objects in the response and it can contain both text and tools in a single response (e.g. Anthropic). The question I have is if you need it to write the plan as a string and call tools in a single call. Wouldn't you want it to wait to call the tools until it's fed the plan in the next call?

**Comment by off6atomic** [comment]
> if you need it to write the plan as a string and call tools in a single call. Wouldn't you want it to wait to call the tools until it's fed the plan in the next call?

Technically it can be combined into a single call. For example, if we do not use function calling feature of OpenAI, we can ask the model with this prompt:
```
Please plan which tools you need and end the conversation with tools that you want to call like the following example:

First I need to use tool 1 to know A, then tool 3 to know B.
---
Tool 1: arguments
Tool 3: arguments
```

Then we can extract the plan and tool calls by splitting the string with `---`. Notice that the model sees the plan before it generates tool calls. OpenAI could internally be doing something like this if they want.

But maybe this approach is not optimized or well-trained so we should use function calling feature instead.

Thanks for the suggestion. I think your your idea of generating a plan using a tool call and streams it to the user is great. It's also how we could implement nested agent. I'll implement this idea.
