### ISSUE TITLE
Tools don't work with Ollama Llama3 8B

### ISSUE THREAD

**Issue by ionflow** [Mirascope/mirascope#320]
### Description

Tried this example with Ollama Llama3 8B (which should support tool calling): https://docs.mirascope.io/latest/concepts/supported_llm_providers/#extractors

```
api_key = "ollama"
base_url = "http://localhost:11434/v1"
call_params = OpenAICallParams(model="llama3")
```

Getting the output: `No tool found in the completion.`

Also setting retries results in the following error:
```
task_details = TaskExtractor(task=task).extract(retries=2)
```

Error:
`RetryError[<Future at 0x1729ed9d0 state=finished raised AttributeError>]`

I also tried retries with: 
```
retries = Retrying(
    before=lambda details: print(details),
    after=lambda details: print(details),
    stop=stop_after_attempt(3),
)
task_details = TaskExtractor(task=task).extract(retries=retries)
```

And get the following output:
```
<RetryCallState 6110636720: attempt #1; slept for 0.0; last result: none yet>
<RetryCallState 6110636720: attempt #1; slept for 0.0; last result: failed (AttributeError No tool found in the completion.)>
<RetryCallState 6110636720: attempt #2; slept for 0.0; last result: none yet>
<RetryCallState 6110636720: attempt #2; slept for 0.0; last result: failed (AttributeError No tool found in the completion.)>
<RetryCallState 6110636720: attempt #3; slept for 0.0; last result: none yet>
<RetryCallState 6110636720: attempt #3; slept for 0.0; last result: failed (AttributeError No tool found in the completion.)>
RetryError[<Future at 0x16c3ea090 state=finished raised AttributeError>]
```

I confirmed that basic chat calls work as expected (using the [BookRecommender](https://docs.mirascope.io/latest/concepts/supported_llm_providers/#__tabbed_1_1)) example.

### Python, Mirascope & OS Versions, related packages (not required)
```
mirascope = {extras = ["all"], version = "^0.16.1"}
```

**Comment by willbakst** [comment]
My understanding is that `llama3` isn't trained for tool calling? I'm not sure if Ollama has added support for tool calling with `llama3`.

**Comment by ionflow** [comment]
Llama3 supports json mode, so I guess regardless of it supporting tool calling (which I don't know if it does) it would be nice to be able to call an extractor in json mode: https://github.com/ollama/ollama/blob/main/docs/api.md#request-json-mode

**Comment by willbakst** [comment]
Ah, yeah it works with json mode, you just need to set it to json mode. The following worked for me:

```python
from pydantic import BaseModel

from mirascope.openai import OpenAICallParams, OpenAIExtractor


class Book(BaseModel):
    """Returns a formatted recommendation for the book `title` by `author`."""

    title: str
    author: str


class BookRecommender(OpenAIExtractor[Book]):
    extract_schema: type[Book] = Book
    prompt_template = "Recommend a {genre} book"

    genre: str

    api_key = "ollama"
    base_url = "http://localhost:11434/v1"
    call_params = OpenAICallParams(
        model="llama3", response_format={"type": "json_object"}
    )


recommender = BookRecommender(genre="fantasy")
book = recommender.extract()
print(book)
```

**Comment by petri** [comment]
Would be good to mention this in the docs. I was just looking for more info on using Ollama, since many pretty good models run surprisingly well even on my intel MacBook Pro.

**Comment by willbakst** [comment]
I opened a new issue #716 to track adding better documentation around using Mirascope with local models.
