### ISSUE TITLE
Is it possible to log error of tool calling in Logfire?

### ISSUE THREAD

**Issue by off6atomic** [Mirascope/mirascope#332]
### Question

I just want to know best practices on how we can log errors that happen during the chatbot conversation including tool calling error (or OpenAI error such as invalid image or too many tokens). 

LangChain seems to do this automatically because they call the tools for us.

**Comment by willbakst** [comment]
For general OpenAI errors you can use the [`with_logfire`](https://docs.mirascope.io/latest/integrations/logfire/) decorator on any of the existing classes, then all of your calls will get logged (including errors).

When calling tools, if the LLM makes a mistake then `response.tool` could throw a ValidationError. If the tool is called successfully, actually running the tool (e.g. `tool.fn(**tool.args)`) could still throw an error (e.g. your tool hits an external API that throws an error). In both cases you can wrap the call and any errors in a [`logfire.span`](https://docs.pydantic.dev/logfire/guides/onboarding_checklist/add_manual_tracing/).

Is this what you're looking for?

**Comment by off6atomic** [comment]
Yes, that is what I'm looking for. Thank you.
