### ISSUE TITLE
Adding Support for Groq

### ISSUE THREAD

**Issue by KTS-o7** [Mirascope/mirascope#344]
### Description

As of now Groq is providing free API keys for Llama3 models. As a student it's a godsend. 
Mirascope provides easy development and learning , hence would love to contribute a groq integration as i get some time.

Would be wonderful if i get assigned. But I need to extensively read the Mirascope code base first.
Kudos to the dev team of Mirascope tho !

**Comment by willbakst** [comment]
Hi! We already support Groq in v0 as well as the upcoming v1 release :)

https://docs.mirascope.io/latest/concepts/supported_llm_providers/

**Comment by willbakst** [comment]
@KTS-o7 thank you for your kind words. We would love for you to contribute. I'm hoping with the upcoming v1 release that we will be able to flesh out some more good first issues that you could help us out with.
