### ISSUE TITLE
Add Postgres/pgvector vectorstore capabilities

### ISSUE THREAD

**Issue by hyusap** [Mirascope/mirascope#347]
### Description

main consideration is that a lot of repos already have use postgres for structured data and pgvector has proven itself to work incredibly well for early-medium scale projects. would be great to reuse existing database infra with mirascope easily

## Useful Resources:
- [main repo](https://github.com/pgvector/pgvector)
- [blog post](https://www.timescale.com/blog/postgresql-as-a-vector-database-create-store-and-query-openai-embeddings-with-pgvector/)
- [supabase support](https://supabase.com/vector)

**Comment by willbakst** [comment]
I would love to support Postgres/pgvector. It's definitely on our radar for future work on RAG, which will be in beta with the v1 release and hopefully out of beta soon.

Is there an integration here you're hoping for beyond the vector store stuff? Would love any additional info around usage you're looking for so we can make sure to design the integration properly.

**Comment by hyusap** [comment]
haven't messed around with rag in mirascope too much, so wouldn't be the best to speak on this but hopefully should be customizeable enough to add custom attributes more than just vector and data. namespacing (if thats the right term?) to seperate vectors by categories in the same table could also be useful

**Comment by willbakst** [comment]
Ok, so IIUC it sounds like you want a single-order higher level abstraction on top of pgvector that makes using it with LLMs/Mirascope easier.

In my mind, the integration I imagine would be something that would slot in very nicely with an existing Postgres database just with new tables or something. I would like to support essentially everything you could do if you did everything yourself like adding a namespace column.

I will think on this and come back with an EDD here to discuss to see if we like the plan before we move forward. Just to be clear, we likely won't get to this at least for a few weeks as we push to release v1, so bear with us on our timeline :)

**Comment by tux-type** [comment]
I would prefer to see mirascope remain a lightweight LLM-only library. It's a breath of fresh air in the currently bloated LLM abstraction ecosystem.

RAG requires a different approach, and users that might use it in production would probably prefer a custom or highly customised solution anyway. I think a _mirascopic_ library that fits in nicely alongside might be a good way to do both :)

**Comment by willbakst** [comment]
I agree with you. I want Mirascope to remain simple and clean, focused on the single-layer abstractions. Potentially also second-layer abstractions e.g. agents, which we're currently thinking through, but I'm not yet certain about.

I'm currently leaning toward either (1) including RAG stuff as part of [lilypad](https://github.com/Mirascope/lilypad) in the future, or (2) creating an entirely separate library as you've mentioned.

The reason I bring up (1) is that RAG feels very much so an integral part of prompt engineering, so as a prompt engineering framework `lilypad` seems like a great place for the functionality to live.

Would love your thoughts.

**Comment by willbakst** [comment]
After further thinking, I think retrieval and other RAG related stuff belongs in a separate library purpose-built for RAG. As @tux-type mentioned, we could implement it the mirascope way, but that doesn't mean it belongs in Mirascope.

I hope to keep Mirascope lightweight and focused on LLM interactions (e.g. `call` decorator and surrounding utilities).

I'm moving to close this issue unless there's a strong case to implement this work as part of this library.
