### ISSUE TITLE
Can't use Pinecone embeddings (dependency issue?)

### ISSUE THREAD

**Issue by mattyweb** [Mirascope/mirascope#349]
### Description

Pinecone has now added its Inference API which includes various embedding models. Support for this is in a new Pinecone plug-in (`pinecone-plugin-inference`). Unfortunately, there is a dependency conflict that makes it impossible to add this plug-in while using Mirascope.

```
Because no versions of pinecone-plugin-inference match >0.4.1,<0.5.0
 and pinecone-plugin-inference (0.4.1) depends on pinecone-client (>=4.1.1,<6.0.0), pinecone-plugin-inference (>=0.4.1,<0.5.0) requires pinecone-client (>=4.1.1,<6.0.0).
And because mirascope (0.18.1) depends on pinecone-client (>=3.2.2,<4.0.0)
 and no versions of mirascope match >0.18.1,<0.19.0, pinecone-plugin-inference (>=0.4.1,<0.5.0) is incompatible with mirascope (>=0.18.1,<0.19.0).
So, because mirascope-demo depends on both mirascope (^0.18.1) and pinecone-plugin-inference (^0.4.1), version solving failed.
```

Please consider updating the pinecone-client version (and perhaps adding explicit support for embeddings using the Pinecone Inference API).

### Python, Mirascope & OS Versions, related packages (not required)

```TOML
mirascope (0.18.1)
Python 3.10.6
```

**Comment by willbakst** [comment]
Hi @mattyweb

Thank you for bringing this to our attention. Are you using our Pinecone integration? Or are you using Pinecone directly?

**Comment by willbakst** [comment]
I just released v0.18.2, which should fix this for now.

With the upcoming v1 release we are going to keep our RAG stuff in beta as we continue to iterate on the interface. We will look into adding more native support for the inference plugin as you mentioned.

**Comment by mattyweb** [comment]
Thanks! I was successfully able to install the plugin after upgrading Mirascope.

> Thank you for bringing this to our attention. Are you using our Pinecone integration? Or are you using Pinecone directly?
I was generating embeddings separately and putting them in the vector DB using Pinecone directly. I didn't see Pinecone examples in the docs but will dig around a bit more now that I can use their embedding models too.

**Comment by willbakst** [comment]
Hmm, ok this is good to know. Since Pinecone is an optional dependency, if you're not using our Pinecone integration, then there shouldn't be a conflict on the versions.

I will have to look into this in the v1 release to ensure that this is the case. The same is true for all other packages. Thank you for letting us know.
