### ISSUE TITLE
blank lines at top of prompt versions when saving with CLI 

### ISSUE THREAD

**Issue by brianpark0126** [Mirascope/mirascope#36]
---

## Describe the bug:
multiple blank lines at the top of each prompt version when saving using Mirascope CLI. Loading them in loads in the blank lines as well.

---

**To Reproduce**

This is my actual prompt.
<img width="332" alt="Screen Shot 2024-01-25 at 7 41 31 PM" src="https://github.com/Mirascope/mirascope/assets/18754854/01c49a8c-87df-45dc-b948-257617a84623">

I now call `mirascope add my_prompt` and it gets saved to `mirascope/versions/` as such:

<img width="381" alt="Screen Shot 2024-01-25 at 7 41 53 PM" src="https://github.com/Mirascope/mirascope/assets/18754854/e51c63ed-50a9-4593-8e3d-4b0241b61683">

After making an edit to my (true, living in `prompts`) prompt, I want to go back to my previous version so i call `mirascope use my_prompt 000X` and what loads in is this:

<img width="255" alt="Screen Shot 2024-01-25 at 7 40 40 PM" src="https://github.com/Mirascope/mirascope/assets/18754854/2761c8f2-e1c3-4af1-9f1d-e3e749b4e327">

**Expected behavior**
blank lines should not be saved into versions nor loaded back from saved versions.

**Comment by willbakst** [comment]
Please include screenshots
