### ISSUE TITLE
v1 docs install instructions suggest to install version `1.0.0-b3`

### ISSUE THREAD

**Issue by jimkring** [Mirascope/mirascope#371]
### Description

[v1 docs installation instructions](https://docs.mirascope.io/1.0.0-b3/#installation) suggest to install version `1.0.0-b3`

```
pip install "mirascope[openai]==1.0.0-b3"     # e.g. `openai.call`
pip install "mirascope[anthropic]==1.0.0-b3"  # e.g. `anthropic.call`
```

This is not the latest beta version.

**Comment by willbakst** [comment]
This is updated in the README in the v1 branch, but `b5` hasn't has a docs release yet as I'm working on the updated docs. I'm hoping to release the updated docs some time this week and will post here when I do.
