### ISSUE TITLE
(unintended usage) manually deleting most recent prompt shuts down ability to keep saving prompts 

### ISSUE THREAD

**Issue by brianpark0126** [Mirascope/mirascope#38]
---

## Describe the bug:
If you manually delete the most recent version of a prompt you have been saving before, you lose the ability to keep saving this prompt. Making a call to `mirascope add my_prompt` will only produce FileNotFounderror from then on. Only apparent workaround I have found is to rename the filename which containts the prompt. 
---

**To Reproduce**

Say you have `my_prompt 0001` through to `my_prompt 0005` (if you were to call `mirascope add my_prompt` it would then generate `my_prompt 0006`).  
Click `my_prompt 0005` in your navigator and move the file to trash
Try `mirascope add my_prompt`

**Expected behavior**
the prompt should still be saved to `mirascope/versions/my_prompt`, either as version 0005 or 0006.

**Comment by willbakst** [comment]
@brenkao feels like the solution here is `mirascope remove my_prompt latest` or `mirascope remove my_prompt 0005`?

**Comment by brenkao** [comment]
if you are deleting a prompt manually, then you will need to manually update the versions.txt `CURRENT_REVISION`. Adding a remove command would do this automatically and is on our backlog.
