### ISSUE TITLE
TypeError: Cannot instantiate typing.Union

### ISSUE THREAD

**Issue by conql** [Mirascope/mirascope#386]
### Description

Mirascope is not compatible with the latest update from openai-python. 

The type ResponseFormat is updated 5 days ago from this [commit](https://github.com/openai/openai-python/commit/bf1ca86cf392eb0ffed1e146937c5d73d8a568f0)
![image](https://github.com/user-attachments/assets/0fceed37-7342-43dd-aaa5-ef0d9160fd52)

Problematic code:
![image](https://github.com/user-attachments/assets/9b21ddb6-5f4d-497d-8613-c92fe6545a7e)

Which will raise: TypeError: Cannot instantiate typing.Union

Temporary fix:
pip install openai==1.39.0

**Comment by willbakst** [comment]
This should be resolved now in `v0.18.3`
