### ISSUE TITLE
Support for models deployed on Azure AI Studio

### ISSUE THREAD

**Issue by vintrocode** [Mirascope/mirascope#388]
### Description

Azure has an offering separate from the OpenAI Studio that allows you to deploy basically every other model outside of OpenAI's. I deployed a Llama-3.1-405B-Instruct endpoint (following [this guide](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/deploy-models-llama?tabs=meta-llama-3-1&pivots=programming-language-python#meta-llama-chat-models)) and I'd love to use Mirascope for interacting with it. I imagine it'd be similar to the azure client wrapper, but not entirely sure.

**Comment by willbakst** [comment]
Just took a look at the guide. It looks like it's not an OpenAI compatible endpoint but a separate Azure endpoint, which means the client wrapper won't work.

Instead, we would likely implement support specifically for the Azure SDK (like we do for all other providers).

I've put this into the v1.1 milestone :)

**Comment by willbakst** [comment]
This is released in `v1.2`!
