### ISSUE TITLE
Best practice to write a cache decorator

### ISSUE THREAD

**Issue by albcunha** [Mirascope/mirascope#393]
### Question

Is there a recomended or suggested way to create a simple cache wrapper on function calls? I was able to do it like this, but I don´t know if there is a better way for it:
```python
import hashlib
import json
import os
import pickle
import sqlite3

from mirascope.base.ops_utils import wrap_mirascope_class_functions
from mirascope.openai import OpenAICallResponse

from architecture.settings import azure_config


def com_cache_de_prompt(cls):
    """Decora classes do Mirascope para automaticamente fazer um cache de resultados de inferência no LLM.
    Exemplo:

    ```python
    from mirascope.openai import OpenAICall
    from services.prompts.sqlite_cache.sqlite_cache import (
        com_cache_de_prompt,
    )


    @com_cache_de_prompt
    class AzureOpenaiCallExtracao(OpenAICall):
        call_params = OpenAICallParams(
            model=azure_config.OPENAI_LLM_MODEL, temperature=0
        )
        configuration = BaseConfig(
            client_wrappers=[
                azure_client_wrapper(
                    api_key=azure_config.OPENAI_API_KEY,
                    organization=azure_config.SUBSCRIPTION_ID,
                    azure_endpoint=azure_config.OPENAI_ENDPOINT,
                    azure_deployment=azure_config.OPENAI_DEPLOYMENT,
                    api_version=azure_config.OPENAI_API_VERSION,
                ),
            ]
        )
    ```
    """
    wrap_mirascope_class_functions(
        cls,
        decorator=cache_em_sqlite(),
    )
    if cls._provider and cls._provider == "openai":
        cls.configuration = cls.configuration.model_copy(
            update={
                "client_wrappers": [
                    *cls.configuration.client_wrappers,
                    "cache_prompt",
                ]
            }
        )
    else:
        raise ValueError("PROVEDOR NÃO CONFIGURADO PARA CACHE")
    return cls

def cache_em_sqlite():
    """
    Memoriza a classe de prompt do mirascope, os argumentos passados e o prompt, e salva o resultado.
    Quando a pesquisa com os mesmos criterios é feita novamente, ele retorna o valor já armazenado
    """
    filename = "prompt_cache.db"
    db_conn = sqlite3.connect(filename)
    db_conn.execute("CREATE TABLE IF NOT EXISTS cache (hash TEXT PRIMARY KEY, result TEXT)")

    def cacheador(func):
        def wrapped(*args):
            # Compute the hash of the <function name>:<argument>
            parametros_para_salvar = args[0].dict()
            parametros_para_salvar["modelo_llm"] = args[0].call_params.model
            # optei por pickle.dumps por ser o mais perfomático
            # adicionamos o nome do modelo, pq ele pode mudar e podemos ter uma resposta diferente.
            conteudo_binario = pickle.dumps(parametros_para_salvar)
            arg_hash = hashlib.sha256(conteudo_binario).hexdigest()

            # Check if the result is already cached
            cursor = db_conn.cursor()
            cursor.execute("SELECT result FROM cache WHERE hash = ?", (arg_hash,))
            row = cursor.fetchone()
            if row is not None:
                nome_da_classe_que_chamou_a_funcao = args[0].__class__.__name__
                print(
                    f"[CACHE][{nome_da_classe_que_chamou_a_funcao}] Prompt cache found. Hash: {arg_hash}. Returning stored result."
                )
                dict_response = json.loads(row[0])
                openai_response = OpenAICallResponse(**dict_response)
                return openai_response

            # Compute the result and cache it
            result = func(*args)
            cursor.execute(
                "INSERT INTO cache (hash, result) VALUES (?, ?)",
                (arg_hash, json.dumps(result.dict())),
            )
            db_conn.commit()

            return result

        return wrapped

    return cacheador
```

**Comment by willbakst** [comment]
To make sure I'm understanding correctly, it looks like you want to return the cached value if the prompt (after template formatting) is exactly the same as a previously run call?

This isn't something that we support natively yet, but it's definitely something I'm interested in looking into. In v1 this should be extremely easy to implement as a custom decorator and may not even need native support (where the implementation would look similar to what you've posted).

**Comment by albcunha** [comment]
Thanks!
