### ISSUE TITLE
Support for Gemini VertexAI Client

### ISSUE THREAD

**Issue by ramon-prieto** [Mirascope/mirascope#410]
### Description

VertexAI provides a custom endpoint for Gemini models. Can we support the vertexai client on Gemini calls

VertexAI also provides a `GenerativeModel` class with similar behavior to the gemini sourced class.

Alternatively, vertexai uses the same class for accessing custom/open-source models deployed within a GCP project. A seperate `vertexai_call` would also make sense if we want to enable access to those too and not just gemini

**Comment by willbakst** [comment]
Yeah I think a separate `vertex` module is likely the best path forward here.

I'm adding this to the `v1.1` milestone.

**Comment by willbakst** [comment]
This is released in `v1.2`!
