### ISSUE TITLE
Error calling `with_langfuse`

### ISSUE THREAD

**Issue by ramon-prieto** [Mirascope/mirascope#424]
### Description

Trying the demo with langfuse and seeing the following error

```
TypeError: with_langfuse() missing 1 required positional argument: 'fn'
```

My code looks like this

```
@with_langfuse()
@anthropic.call("claude-3-5-sonnet@20240620")
@prompt_template(prompt.prompt)
def recommend_book(genre: str):
    ...
```

### Python, Mirascope & OS Versions, related packages (not required)

```TOML
Python 3.12.4
Mirascope 1.0.0b6
```

**Comment by willbakst** [comment]
This is due to an update with the decorator. This will be fixed in the release (coming now!)
