### ISSUE TITLE
Dynamic Validation based on prompt variables

### ISSUE THREAD

**Issue by anthony2261** [Mirascope/mirascope#493]
### Question

Hello! Thanks for the great library.

I need to do validation depending on the input. Here's a simplified example of what I'm trying to achieve:
```python
class Emotions(BaseModel):
    emotions: list[str]

@openai.call(..., response_model=Emotions, ...) # for brevity
@prompt_template(
    """
    You are given a list of sentences. Return a list containing an emotion for each of these sentences:
    {sentences}
    """
)
def get_emotions(sentences: list[str]): ...
```
I would like to have a validation that the length of the input equals the length of the output. The way I'm doing this at the moment is via a nested function call, like this:

```python
def get_emotions(sentences: list[str]):
    class Emotions(BaseModel):
        emotions: list[str]

    @model_validator(mode="after")
    def validate_output_length(self) -> Self:
        if len(sentences) != len(self.emotions):
            raise ValueError("length mismatch bla bla bla...")
        return self

    @openai.call(... same as before ...)
    @prompt_template(... same as before ...)
    def get_emotions_inner(sentences: list[str]): ...

    return get_emotions_inner(sentences)
```

Is there a better/cleaner way to do this?

Thanks again 😃

**Comment by willbakst** [comment]
Unfortunately this isn't possible right now and you'll need to use nested functions. However, in this case I would likely just do the validation after the LLM call, for example:

```python
class Emotions(BaseModel):
    emotions: list[str]

@openai.call(... same as before ..., response_model=Emotions)
@prompt_template(... same as before ...)
def classify_emotions(sentences: list[str]): ...

def get_emotions(sentences: list[str]) -> Emotions:
    emotions = classify_emotions(sentences)
    if len(sentences) != len(emotions):
        # handle mismatch
    return emotions
```

This does make me wonder though if we could implement something like this:

```python
class Emotions(BaseModel):
    sentences: Annotated[list[str], FromCallArgs()]
    emotions: list[str]
```

where we would exclude `sentences` from the tool schema because we want to use the call argument instead (and then you would have access to `sentences` inside the model and could write all the validators as you have them written except without the nesting workaround).

**Comment by anthony2261** [comment]
Thanks for your response!
>I would likely just do the validation after the LLM call

Only reason why I don't want to do that is because I'm doing auto retries with tenacity and auto adding the errors in the prompt.

I'm ok with the nested function, but it would definitely be great if there was such a thing as `FromCallArgs` just for convenience 🙂

**Comment by willbakst** [comment]
Ah ok I see. In the meantime while we think through this feature, you can still use tenacity with the errors. It would look something like this:

```python
class Emotions(BaseModel):
    emotions: list[str]

@openai.call(... same as before ..., response_model=Emotions)
@prompt_template(... same as before ...)
def classify_emotions(sentences: list[str], *, errors: list[ValueError] | None = None): ...

@tenacity(stop=..., after=collect_errors(ValueError))
def get_emotions(sentences: list[str], *, errors: list[ValueError] | None = None) -> Emotions:
    emotions = classify_emotions(sentences, errors)
    if len(sentences) != len(emotions):
        # handle mismatch
        raise ValueError(...)
    return emotions
```

**Comment by anthony2261** [comment]
Ohh that's way cleaner than I had implemented it, thank you!
