### ISSUE TITLE
Anthropic cost coverage for AWS bedrock and Vertex

### ISSUE THREAD

**Issue by ramon-prieto** [Mirascope/mirascope#501]
### Description

Currently, the calculate cost function only accepts the naming convention from the official Anthropic API. Can we extend the cost mapping to allow for cost estimation on workflows using either the Vertex or Bedrock clients?

https://github.com/Mirascope/mirascope/blob/dev/mirascope/core/anthropic/_utils/_calculate_cost.py#L20

**Comment by willbakst** [comment]
A bit swamped this week, but will try to look into this next week.

PR welcome if you have the time and want to contribute!

Would be much appreciated :)

**Comment by ramon-prieto** [comment]
Created this [PR](https://github.com/Mirascope/mirascope/pull/504) to extend the mapping
