### ISSUE TITLE
Mistral Vision Support

### ISSUE THREAD

**Issue by willbakst** [Mirascope/mirascope#521]
### Description

Mistral recently released a new vision model Pixtral. The API looks extremely similar to other providers such as OpenAI, so adding support should be fairly straightforward.

Just need to update [this conversion code](https://github.com/Mirascope/mirascope/blob/912d8d3a5b1fd1845c38148117b1158b15f09623/mirascope/core/mistral/_utils/_convert_message_params.py#L18) to support image parts [like we do for OpenAI](https://github.com/Mirascope/mirascope/blob/912d8d3a5b1fd1845c38148117b1158b15f09623/mirascope/core/openai/_utils/_convert_message_params.py#L24)

**Comment by skylarbpayne** [comment]
I'll take a crack at this.

**Comment by willbakst** [comment]
This is released in `v1.10`!
