### ISSUE TITLE
Production Deployment Best Practices Documentation

### ISSUE THREAD

**Issue by willbakst** [Mirascope/mirascope#523]
### Description

We should include documentation specifically around best practices to deploy apps built using Mirascope to production.

This should cover things like error handling, retries, and more.

For anyone already deploying to production, feedback and input would be much appreciated here!

**Comment by joekendal** [comment]
with aws serverless constructs, we would be looking to have adapters for the stateful and stateless components:

memory: dynamodb
compute: lambda

**Comment by willbakst** [comment]
You should be able to use lambda to run the calls, and then pull chat history from dynamodb and insert it as a computed field.

 The idea is that inside of your call you would pull the chat history from dynamo.

In the upcoming `v1.3` release, this will be more clear when using prompt writing methods like messages shorthand.

Does this make sense?

**Comment by willbakst** [comment]
Give that Mirascope lives as a single-layer abstraction on top of LLM APIs, I don't believe this is the right place for "deployment" best practices to live.

As mentioned in earlier comments, Mirascope is extremely flexible, and since everything is written as functions it plays nicely with whatever system you want to use to deploy your LLM application.

We will likely work on some form of additional deployment features as part of [`Lilypad`](https://github.com/Mirascope/lilypad), so I'll leave future work on this documentation/guide to that library.

Feel free to reopen this issue if you have ideas for what should live specifically in the Mirascope library and why it should live here.
