### ISSUE TITLE
`learn/response_models/few_shot_examples/openai` examples do not work.

### ISSUE THREAD

**Issue by jstpierref** [Mirascope/mirascope#554]
### Description

The response content output by `gpt-4o-mini` is:
```
{
  "examples": [
    {
      "author": "Sanderson, Brandon",
      "title": "THE WAY OF KINGS"
    }
  ]
}
```

instead of 
```
{
  "title": "THE WAY OF KINGS",
  "author": "Sanderson, Brandon"
}
```

The LLM doesn't seem to handle JSON schema top-level `examples` properly. 

### Python, Mirascope & OS Versions, related packages (not required)

```TOML
Python 3.10.15
Mirascope from origin/dev (commit fbe8ee1fa3c11fff07bfe6ff858a0412ec96ff59)
macOS Sonoma 14.6
```

**Comment by willbakst** [comment]
Ah ok this is good to know. I'll need to play around with this to see what the underlying issue is.

If the issue is with the model itself not handling top level examples I'll update the examples and docs to make this more clear.

Thanks for pointing this out!

**Comment by willbakst** [comment]
Ok I identified it was an issue with the prompt. I needed to be more clear about how to match the format (i.e. exclude the 'examples' key). The examples should now work (or at least did in my testing).
