### ISSUE TITLE
Langfuse integration: Model input not captured

### ISSUE THREAD

**Issue by jannikmaierhoefer** [Mirascope/mirascope#587]
### Description

With the upgrade to Mirascope v1, the Langfuse integration does not capture model input correctly. 

Currently, the prompt template is shown as model input in Langfuse ("Recommend a {genre} book") instead of ("Recommend a fantasy book").

Example trace in Langfuse: https://cloud.langfuse.com/project/cloramnkj0002jz088vzn1ja4/traces/e74be43d-d1c9-48b2-a84f-fe5dc7300cf9?observation=b08b154d-079a-4d47-bcdd-e5aea17d7d6e

![CleanShot 2024-10-01 at 18 44 45@2x](https://github.com/user-attachments/assets/993bf3fd-e0a2-468d-9425-b18dbe3da8d9)

**Comment by willbakst** [comment]
Fix released in `v1.2.1` :)
