### ISSUE TITLE
'OpenAIChat has no Attribute 'extract'

### ISSUE THREAD

**Issue by aowen14** [Mirascope/mirascope#59]
---

## Describe the bug:
`OpenAIChat.extract Is not findable in most recent release when installing from Pip

---

**To Reproduce**
`pip install mirascope`

1. `cd cookbook/basic_examples`
2. `python -m extract_book_info.py`

OR Copy and paste the code from that script into a notebook, etc.

OR:
1. Inside a VSCode environment with OpenAIChat imported
2. Chat.extract will not show up in autocomplete, whereas other functionality does.

**Expected behavior**
Shouldn't throw an error when running, and the extract function should show up in autocomplete 

**Screenshots**
<img width="710" alt="Screenshot 2024-02-05 at 10 38 46 AM" src="https://github.com/Mirascope/mirascope/assets/22056542/27347647-b44f-4369-acee-aa611f15dcaf">

- Version: [0.2.1]

**Comment by willbakst** [comment]
@aowen14 I'm not seeing this issue. I just installed `pip install mirascope\[all\]` in a clean environment and see the below:

![Screenshot 2024-02-05 at 6 36 57 PM](https://github.com/Mirascope/mirascope/assets/99370834/ecb22838-1c56-4612-afff-b7e73b07a0b5)

How certain are you that you installed version `0.2.1`?

**Comment by aowen14** [comment]
Quite certain. I think I maybe had install `mirascope`, not `mirascope[all]`, which I didn't realize because there was already some OpenAI functionality in the base package, so I forgot that there is additional OpenAI functionality in the full version

**Comment by willbakst** [comment]
I just ran `pip install mirascope` in a clean environment and still did not see the issue. Of course, `chat.extract` fails but only because I didn't install the `opanai` optional dependencies, but it shows up for autocomplete etc.

I'm going to close this issue for now, but if it persists feel free to reopen with additional info / examples.
