### ISSUE TITLE
Doc site not working

### ISSUE THREAD

**Issue by pat-ben** [Mirascope/mirascope#599]
### Description

Doc site not working. Invalid SSL certificate Error code 526

**Comment by willbakst** [comment]
Thank you for bringing this to our attention! I'm actively working to resolve this. For some reason, GitHub pages is failing to issue a new cert...

<img width="863" alt="Screenshot 2024-10-05 at 7 42 51 AM" src="https://github.com/user-attachments/assets/c1117a44-f0a6-459b-8dc0-d5c664b4e9d3">

**Comment by willbakst** [comment]
Resolved!

Will be working on a longer term fix with the upcoming release of `v1.3` and new documentation
