### ISSUE TITLE
LiteLLM usage tracking

### ISSUE THREAD

**Issue by CharlesFarhat** [Mirascope/mirascope#603]
### Description

When using liteLLM with OpenAI models, cost and token usage tracking do not work on all calls. Calls that takes more than 2 secondes don't report either usage nor cost.
Happy to help !

### Python, Mirascope & OS Versions, related packages (not required)

```TOML
Python 3.12
Mirascope : 1.1.2
```

**Comment by willbakst** [comment]
One of the main issues right now is that we use `OpenAICallResponse` as the response for LiteLLM. We'll need to update to include a new `LiteLLMCallResponse` class that subclasses the OpenAI class and updates the usage property to use https://docs.litellm.ai/docs/completion/token_usage#5-cost_per_token

PR welcome! If you have any questions before getting started, let me know

**Comment by willbakst** [comment]
Hmm, a new PR #608 may fix part of this? Looks like we were missing the most recent model so costs weren't being tracked? Not sure if this is the model you're seeing the issue on.

Regardless, we need to add better cost tracking as mentioned in the previous comment.

**Comment by willbakst** [comment]
Fixed in `v1.7`! Let me know if you have any questions about usage

**Comment by CharlesFarhat** [comment]
Quick question, how do you calculate the input token ? I am trying to create a decorator to store input and output tokens in a very reliable way. If input token is None I am tryin to reconstruct input tokens using tiktoken and the input prompt. How can I do that ?

Rn I have :
```
@contextmanager
def custom_context_manager(
    fn: Callable,
    callback: Callable[[dict], None]
) -> Generator[tuple[Callable, LLMUsage], Any, None]:
    metrics = LLMUsage(
        input_tokens=0,
        output_tokens=0,
        model_used="",
        date=datetime.datetime.now(),
        estimated_cost=0.0
    )
    yield (callback, metrics)

def handle_call_response(
    result: BaseCallResponse, 
    fn: Callable, 
    context: tuple[Callable, LLMUsage] | None
) -> None:
    if context is None:
        return
    
    callback, metrics = context
    metrics = update_usage_from_call_response(metrics, result)
    
    # Execute the callback with the metrics
    callback(metrics)
and trying :
def update_usage_from_call_response(usage: LLMUsage, result: BaseCallResponse) -> LLMUsage:
    if not result.model:
        logger.warning("No model found in call response")
        
    
    if not result.input_tokens:
        logger.warning("No input tokens found in call response")
        input_tokens = tiktoken.encoding_for_model(result.model if result.model else "gpt-4o").encode()
    
    return 
```
How to have the overall prompt send to llm provider in the encode ?

And thx William for 1.7 ! Looking forward to test it !

**Comment by willbakst** [comment]
I'm curious when `input_tokens` is `None`?

If you're using `litellm`, this seems like something that `litellm` should solve? Otherwise you'll need to start figuring out how to handle every single provider message type to reconstruct the input.
