### ISSUE TITLE
Broken links in Tools & Agents tutorials

### ISSUE THREAD

**Issue by orlando21** [Mirascope/mirascope#613]
### Description

The top two links on this page: https://mirascope.com/docs/tutorials/getting_started/tools_and_agents/

... (e.g., "Tools documentation") should link to the respective chapters in the documentation, but it appears that `/tutorials/` has mistakenly been inserted into the URLs, rendering them broken.

**Comment by willbakst** [comment]
Fixed! Thank you for pointing this out :)
