### ISSUE TITLE
Create llms.txt file for Mirascope documentation

### ISSUE THREAD

**Issue by betterthanever2** [Mirascope/mirascope#630]
### Description

As Mirascope documentation grows, it becomes harder to navigate and keep up to. There is this thing called [`llms.txt`](https://llmstxt.org/). They suggest 

> A proposal to standardise on using an /llms.txt file to provide information to help LLMs use a website at inference time. 

Here's the [relevant part of the FastHTML documentation](https://docs.fastht.ml/#getting-help-from-ai) that explains it a little more. In short, it's a page in Markdown format that contains the entire documentation and that you can feed to an AI agent, and then ask it (them?) questions about it.

Would be really nice to have.

**Comment by willbakst** [comment]
I'll look into this!

**Comment by willbakst** [comment]
Circling back here as I continue to research. One thing I need to figure out is how to do this with mkdocs without impacting the site (e.g. Google really does not like duplicate content, so I need to ensure I do things like remove the `.md` urls from the sitemap etc.).

Generally, I think including something here to make it easier to port our docs into an LLM is worth doing, so I'll continue to think through this and provide updates as I have them.

**Comment by willbakst** [comment]
[mirascope.com/llms.txt](mirascope.com/llms.txt) :)

feel free to reopen this issue or post a new bug issue if there are any problems with how we did it
