### ISSUE TITLE
Fails to run on Python 3.13.

### ISSUE THREAD

**Issue by petri** [Mirascope/mirascope#636]
### Description

Typing fails in two places with `TypeError: Plain typing.Annotated is not valid as type argument`

First place: mirascope/core/base/_utils/_protocols.py, line 42:

`_ResponseModelT = TypeVar(
    "_ResponseModelT", bound=BaseModel | BaseType | Enum | Annotated
)`

Second: mirascope/core/base/_call_factory.py, line 39, exactly same code so defined twice...

Simply removing the `Annotated` from both places removes the failures. Not sure what's been the intented use this way. It seems to me using it this way makes no sense?

### Python, Mirascope & OS Versions, related packages (not required)

```TOML
Python: 3.13
Mirascope: a few latest versions up to 1.6.0
```

**Comment by willbakst** [comment]
The intended use here is to enable validation on built-in response model types, but I'm realizing that this typing doesn't work anyway, (and you can still use e.g. `Annotated[str, AfterValidator(...)]` as a built-in type response model successfully without this bounding, it just requires a type ignore, which it requires anyway)

Thanks for pointing this out!

I will begin working on a fix for this asap

**Comment by willbakst** [comment]
I just released the fix for this in `v1.6.1`. Let me know if you have any other issues here.

Note that there may still be some optional dependencies that themselves don't support `3.13`
