### ISSUE TITLE
Typing for Call Decorator breaks down when used as a function

### ISSUE THREAD

**Issue by RamiAwar** [Mirascope/mirascope#637]
### Description

It seems like typing for this decorator is not right when used as a function. I'm trying to use it as specified in the multi-provider docs (I'd like to have a dynamic provider + API key + base URL etc.).

It works well as a decorator though.

<img width="858" alt="image" src="https://github.com/user-attachments/assets/6fb2a4c3-c1ff-4f8d-87ae-c5d69b5aaadc">

### Python, Mirascope & OS Versions, related packages (not required)

```TOML
Python 3.11
Latest mirascope (1.6.0)
MacOS
```

**Comment by RamiAwar** [comment]
Ah seems like the problem is with my BaseModel response_model typing. It works if I specify a specific model.

Not an issue with mirascope then, will look into fixing the types.
<img width="888" alt="image" src="https://github.com/user-attachments/assets/03e0469c-854b-44aa-9c2a-622d94eee83e">

**Comment by willbakst** [comment]
Glad you found it!
