### ISSUE TITLE
Option to reuse custom client with a call decorator

### ISSUE THREAD

**Issue by tux-type** [Mirascope/mirascope#643]
### Description

As shown in the example below, to use a custom client one has to create the instance at the module level, which is then reused within the module. However, when importing this module elsewhere this also triggers the `client = OpenAI()` call.

```
from mirascope.core import openai
from openai import OpenAI

client = OpenAI(
    api_key="ollama",
    base_url="http://localhost:11434/v1",
)

@openai.call("MODEL_NAME_HERE", client=client)
def recommend_book(genre: str) -> str:
    return f"Recommend a {genre} book"
```

\
\
It would be good to have an option to create or otherwise specify the custom client without triggering the `OpenAI()` call on import. One option is to use partial:
```
from mirascope.core import openai
from openai import OpenAI
from functools import partial

client = partial(
    OpenAI, 
    api_key="ollama",
    base_url="http://localhost:11434/v1",
)

@openai.call("MODEL_NAME_HERE", client=client())
def recommend_book(genre: str) -> str:
    return f"Recommend a {genre} book"
```

However, this ends up calling the creation of the client on every function call. This might get somewhat expensive with many calls (?).

It would be nice to be able to lazy load the client once on first call, then reuse subsequent times. Bonus if this custom client is easily reusable between modules.

**Comment by willbakst** [comment]
I think the best way to solve this would be to implement a feature for setting the client through the dynamic config.

```python
from mirascope.core import BaseDynamicConfig, Messages, openai
from openai import OpenAI

@openai.call("gpt-4o-mini")
@prompt_template("Recommend a {genre} book")
def recommend_book(genre: str) -> BaseDynamicConfig:
    return {
        "messages": [Messages.User(f"Recommend a {genre} book")],
        "client": OpenAI(...),
    }
```

This would enable passing the client to the function as an argument, which I believe would satisfy all of your needs:

```python
from mirascope.core import BaseDynamicConfig, Messages, openai
from openai import OpenAI

@openai.call("gpt-4o-mini")
@prompt_template("Recommend a {genre} book")
def recommend_book(genre: str, *, client: OpenAI | None = None) -> BaseDynamicConfig:
    if not client:
        client = OpenAI()
    return {
        "messages": [Messages.User(f"Recommend a {genre} book")],
        "client": client,
    }
```

If this works, let me know and we'll work to get this included in the `v1.7` release this Friday :)

**Comment by tux-type** [comment]
Yes, this looks good. Impressed by how fast this is being worked on!

Would this solution work with the string prompt template by any chance? No problem if not.

**Comment by willbakst** [comment]
All prompt writing methods work with dynamic configuration, so this will also work with string templates :)

**Comment by willbakst** [comment]
Ok, functionality has been implemented. We will release this in `v1.7` on Friday, and I'll circle back here to close the issue once it's released :)
