### ISSUE TITLE
Catch ValueError and attach the error to it

### ISSUE THREAD

**Issue by CharlesFarhat** [Mirascope/mirascope#659]
### Description

When there is a ValueError (i.e. when No tool call or JSON value), we don't attach e._response, maybe catch the error and attach the response to it. makes error handling better :)

**Comment by willbakst** [comment]
This should be as simple as moving [this line](https://github.com/Mirascope/mirascope/blob/b4f791f9f11b3c1d7a19e825818390bbe0b232bb/mirascope/core/base/_extract.py#L135) inside of the try/except block and updating the block to catch all errors (instead of just `ValidationError`)

**Comment by willbakst** [comment]
This is released in `v1.8`!
