### ISSUE TITLE
Support for calling OpenRouter endpoint

### ISSUE THREAD

**Issue by srajangarg** [Mirascope/mirascope#703]
### Description

I, along with many others, use https://openrouter.ai/ to route their API traffic to different LLMs using a single API key. Would be nice to allow using it

**Comment by willbakst** [comment]
You can do this using a [custom client](https://mirascope.com/learn/calls/#custom-client) with `openai.call`:

```python
from mirascope.core import openai
from openai import OpenAI

client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key="$OPENROUTER_API_KEY",
)

@openai.call("gpt-4o-mini", client=client)
def recommend_book(genre: str) -> str:
    return f"Recommend a {genre} book"

response = recommend_book("fantasy")
print(response.content)
```
