### ISSUE TITLE
Add support for Anthropic's Model Context Protocol

### ISSUE THREAD

**Issue by betterthanever2** [Mirascope/mirascope#725]
### Description

A few days ago Anthropic open-sourced [Model Context Protocol](https://www.anthropic.com/news/model-context-protocol) which is supposed to serve as a standard for supplying AIs with data of all sorts, from files on local filesystem to databases to git repositories and beyond. 

Mirascope already has some tools for working with filesystems and so forth, and I certainly don't have any troubles using them when trying to enrich my requests with data, yet, I feel like a common, open-source protocol could be a way to go. The implementation definitely looks interesting. 

Do you think this is something Mirascope could be enhanced with?

**Comment by willbakst** [comment]
Definitely interested in this, we're going to look into this.

From a brief glance, it appears that we'll likely want to have some type of Mirascope MCP wrapper for more easily spinning up the MCP servers + additional tooling for actually connecting calls to the server.

**Comment by willbakst** [comment]
Just released support for this in `v1.12` let us know what you think!

docs:
https://mirascope.com/learn/mcp/server/
https://mirascope.com/learn/mcp/client/

**Comment by betterthanever2** [comment]
wow, that was quick
