### ISSUE TITLE
Image support for PIL Images does not work.

### ISSUE THREAD

**Issue by yml** [Mirascope/mirascope#746]
### Description

As [discussed on slack](https://mirascope-community.slack.com/archives/C072S9P1R38/p1734385259750229) the code in place to support `PIL Image` does not work.

This is the kind of use case:

```
@openai.call("gpt-4o-mini")
def generate_caption(img: Image.Image) -> Messages.Type:
    return Messages.User(
        [
            "Generate the caption for the following image",
            img,
        ]
    )


if __name__ == "__main__":
    print("Running image_caption.py")
    with Image.open("./barracuda.jpg") as img:
        print(generate_caption(img))
```

[This is where](https://github.com/Mirascope/mirascope/blob/ff35c81d94376e06728a908c1e4def719e18fc88/mirascope/core/base/_utils/_convert_messages_to_message_params.py#L49) I think the problem is.

### Python, Mirascope & OS Versions, related packages (not required)

```TOML
Linux
python 3.11.9
pillow 11.0.0
mirascope 1.13.0
openai 1.57.4
```

**Comment by willbakst** [comment]
Fix is released in `v1.13.1` :)
