### ISSUE TITLE
Is it possible to load API keys from a .env file

### ISSUE THREAD

**Issue by akumar-xyz** [Mirascope/mirascope#757]
### Question

I'm using the Gemini API and I'm it I'm getting the error saying "API key not valid".

My app looks something like this

```python
from dotenv import load_dotenv

load_dotenv()

# Set other config
```

```python
import src.config
from mirascope.core import BaseMessageParam, Messages, gemini

@gemini.call("gemini-1.5-flash")
def call_thing(message):
    return message
```

But if I load the env variable in my shell before invoking the python code, everything is working is expected

For example:
```sh
export GOOGLE_API_KEY="..."
python src/main.py
```

I tried to find some way to explicitly pass the API key to the call function after loading from .env but looks from the documentation that it does not work.

**Comment by koxudaxi** [comment]
The mirascope library internally uses Google's SDK to make API calls, so there's nothing particularly special happening. While it's interesting that it works when you export the key in the shell, it's difficult to diagnose the exact issue with the information provided.

Although I'm not an expert with dotenv, I suspect this might be related to the timing of when variables are loaded. At the very least, Gemini allows you to configure the API key in Python directly, so you could try the following approach:

```python
from google.generativeai import configure
from mirascope.core import gemini

configure(api_key="your-api-key")

@gemini.call("gemini-1.5-flash")
def call_thing(message):
    return message
```

https://ai.google.dev/gemini-api/docs/quickstart?lang=python#make-first-request

**Comment by akumar-xyz** [comment]
Hey! Thanks for the response!  This was helpful.

Your direction helped with some "printf debugging"

Unfortunately, the issue I was facing is a little stupider than the sequence in which .env is loaded by dotenv.
My `.env` looked something like this

```env
GOOGLE_API_KEY="AIXXXXXXXXXXXXXXXXXXXX"
```
and `dotenv` was loading it reading the variable like so: `"AIXXXXXXXXXXXXXXXXXXXX"` (including the quotes)

Clearly, the answer to "Is it possible to load API keys from a .env file?" is yes
Also, the answer to "Is there some way to explicitly pass the API key?" is yes, but there's no provider-agnostic interface to do this.

Thanks for all the work!
